### ISSUE TITLE
Do not force HTTP for metric list requests

### ISSUE THREAD

**Issue by heyLu** [spreadshirt/prometheus-explorer#1]
Instead of enforcing HTTP for the backend requests to list metric names we should either specify the source as a full URL including the protocol (i.e. with `http://` or `https://`), or at least default to the protocol that the frontend is using.

The JavaScript part does that already ([[1]], [[2]], [[3]]), so let's do it in the backend as well.

Thanks to `reezer` for pointing this out on Lobste.rs!

[1]: https://github.com/spreadshirt/prometheus-explorer/blob/c2e861db1d1285e3731597f342e291dea5695f3e/static/board.js#L386
[2]: https://github.com/spreadshirt/prometheus-explorer/blob/c2e861db1d1285e3731597f342e291dea5695f3e/static/board.js#L444
[3]: https://github.com/spreadshirt/prometheus-explorer/blob/main/static/explore.js#L36

**Comment by peterbourgon** [comment]
+1 — I have a use case which would require this, as well as custom certs, e.g. as cURL

```
curl \
  --cacert my_ca_cert.crt --cert my_cert.crt --key my_key.key \
  --data 'query=count(up) by (job)' https://my.example.com/prometheus/my_segment/api/v1/query
```

Could that also be supported? 😇

**Comment by heyLu** [comment]
Custom certs would be pretty awkward with the current implementation.  But they are certainly worth a thought (and a separate issue).

So far the backend knows nothing about Prometheus servers, everything is parsed and initiated on the client.
